name: ss-api
on:
  push:
    branches: 
      [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Log in to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.SSAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.SSAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: kaaw/ss-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SSAPI_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ss-api -g DefaultResourceGroup-CUS --server docker.io --username  ${{ secrets.SSAPI_REGISTRY_USERNAME }} --password ${{ secrets.SSAPI_REGISTRY_PASSWORD }}
            az containerapp update -n ss-api -g DefaultResourceGroup-CUS --image kaaw/ss-api:${{ github.sha }}
