name: ss-api
on:
  push:
    branches: 
      [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: docker.io
          username: ${{ secrets.SSAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.SSAPI_REGISTRY_PASSWORD }}      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kaaw/ss-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SSAPI_AZURE_CREDENTIALS }}
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ss-api -g DefaultResourceGroup-CUS --server docker.io --username  ${{ secrets.SSAPI_REGISTRY_USERNAME }} --password ${{ secrets.SSAPI_REGISTRY_PASSWORD }}
            az containerapp update -n ss-api -g DefaultResourceGroup-CUS --image kaaw/ss-api:${{ github.sha }}
